### PR TITLE
Update UUID implementation

### PR DESCRIPTION
**Pull request by StijnWoestenborghs**
- Updates MersenneTwister random generator to a struct that keeps state
- Strips uuid from using bytes and moves bytes from 
- Renames UUID type and UUIDGenerator

### CODE REVIEW

**Review by Benny-Nottonson — COMMENTED** [review]
lgtm

**Review by Benny-Nottonson — APPROVED** [review]

**Comment by StijnWoestenborghs** [comment]
Only very minor changes compared to your rework. 
Some for readability, and I brought back `alias W: Int = 32` as there is a 64 bit variant of this. 
Did you do something to the unrolls?

**Comment by Benny-Nottonson** [comment]
They dont really make a performance difference in my testing, not worth

**Comment by StijnWoestenborghs** [comment]
Yeah okay, doesn't matter. I think they are in now

**Pull request merged**
